title: Pattern Kit


namespaces:
  includes: source/_includes
  layouts: source/_layouts
  patterns: source/_patterns
  bolt: public/templates
paths:
  data:
    - public/data
  schemas:
    - public/schemas
  templates:
    - public/templates
  docs:
    - public/docs
  sg:
    - source/_content
extensions:
  data: .data.json
  schemas: .json
  templates: .twig
  docs: .docs.md
  sg: .md
categories:
    - Pattern
    - Component
    - Layout
assets:
  css:
    - /source/styles/style.css
  js:
  footer_js:
